### ISSUE TITLE
希望可以添加archlinuxcn鏡像源

### ISSUE THREAD

**Issue by ghost** [LZUOSS/Mirror#1]
**archlinuxcn**鏡像源包含部分常用軟件的二進制分發包，
[**Arch Linux Chinese Community Repository**](https://github.com/archlinuxcn/repo)
[archlinuxcn]
SigLevel = Optional TrustedOnly
Server = https://cdn.repo.archlinuxcn.org/$arch
希望可以添加**archlinuxcn**源以方便下載。

**Comment by pengsrc** [comment]
您好，已聯繫鏡像站的維護者，他將稍後會與您取得聯繫。

**Comment by lch** [comment]
您好，我们已经开始着手archlinuxcn软件源的同步，该源将在首次同步完成后可用。感谢您对兰州大学开源社区镜像站的支持。

兰州大学开源社区镜像站管理小组

**Comment by lch** [comment]
您好，archlinuxcn已经同步完成。您可以通过 http://mirror.lzu.edu.cn/archlinuxcn/ 访问。感谢您对兰州大学开源社区镜像站的支持。

兰州大学开源社区镜像站管理小组
