### ISSUE TITLE
请问是否还存有玟茵OS的镜像？

### ISSUE THREAD

**Issue by ghost** [LZUOSS/Mirror#11]
`http://www.wenyinos.org/`  从此站过来的，最近在挖掘国内的发行版又遇到了多年前的玟茵，但是应该是实质上弃坑了，但是不了解 “`forum.wenyinos.org/thread-36.htm`” 中指向兰大镜像站的内容是fedora的仓库还是玟茵专有库？如果有现在还能否提供？或者源的地址？

**Comment by lch** [comment]
你提供链接中的时间（2018-2-27）的那个时候镜像站应该也是没有提供玟茵OS的仓库的，那个页面可能为更早期的内容。

**Comment by ghost** [comment]
经过安装查询，玟茵OS软件仓库等同于Fedora，仓库来自兰大，谢谢你们的帮助和坚守。
