### ISSUE TITLE
Please Fix Bug

### ISSUE THREAD

**Issue by ZhiShengYuan** [LZUOSS/Mirror#12]
when i try to access this url <http://mirror.lzu.edu.cn/centos/> it's return this <curl http://mirror.lzu.edu.cn/debian/
curl: (52) Empty reply from server>
and when i try to access this url <https://oss.lzu.edu.cn/wiki/mirror/help>
it give me this info <curl https://oss.lzu.edu.cn/wiki/mirror/help
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /wiki/mirror/help was not found on this server.</p>
</body></html>>

**Comment by lch** [comment]
It is recommended to use **https** address (https://mirror.lzu.edu.cn) instead of http address, because the http might be unstable sometimes.

**Comment by ZhiShengYuan** [comment]
> It is recommended to use **https** address (https://mirror.lzu.edu.cn) instead of http address, because the http might be unstable sometimes.

thx,https is normal
if possible plz fix this page 
> https://oss.lzu.edu.cn/wiki/mirror/help
