### ISSUE TITLE
新增openEuler镜像源的申请

### ISSUE THREAD

**Issue by zhang-jian-jun** [LZUOSS/Mirror#15]
项目名称：
openEuler镜像源

项目简介：
openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展，官网链接：https://openeuler.org/zh/

上游源地址，同步指令：
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)

镜像大小:
多个版本共600G

openEuler社区基础设施团队
官网链接: https://openeuler.org/zh/
镜像链接: https://repo.openeuler.org/

**Comment by prcups** [comment]
我们会尝试在现有架构上加入openEuler镜像
同时我们目前正在对镜像站进行重构，之后openEuler会加入测试中

**Comment by moeyork** [comment]
您好，已添加 openeuler 镜像（[镜像地址](https://mirror.lzu.edu.cn/openeuler/)），感谢您对兰州大学开源社区的支持。

**Comment by zhang-jian-jun** [comment]
您好，非常感谢！

**Comment by zhang-jian-jun** [comment]
@moeyork 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

**Comment by Reset816** [comment]
> @moeyork 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

没有限速。受限于硬件，现在最高速度为1000Mbps，今年晚些时候可能会升级为10000Mbps

**Comment by zhang-jian-jun** [comment]
好的，谢谢哈

**Comment by zhang-jian-jun** [comment]
@Reset12138 ,咨询一下，镜像站点，有没有提供我们这边统计openEuler镜像源资源下载量的接口或者数据导出功能？

**Comment by Reset816** [comment]
> @Reset12138 ,咨询一下，镜像站点，有没有提供我们这边统计openEuler镜像源资源下载量的接口或者数据导出功能？

抱歉，镜像站暂时不提供该功能

**Comment by zhang-jian-jun** [comment]
@Reset12138 
非常感谢使用我们openEuler镜像源，镜像源的同步指令，不再需要用户名和密码，
直接输入：
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
即可完成镜像源的同步，
谢谢！
