### ISSUE TITLE
新增Anaconda镜像申请

### ISSUE THREAD

**Issue by lizhaoguosina** [LZUOSS/Mirror#16]
校园网内访问清华镜像源 [https://mirrors.tuna.tsinghua.edu.cn/anaconda] / 北外镜像源 [https://mirrors.bfsu.edu.cn/anaconda] 速度较慢且不稳定
可以选择清华镜像站作为上游
请注意，对外提供Anaconda镜像可能需要提前与Anaconda公司联系并取得授权

**Comment by Reset816** [comment]
镜像站刚买了硬盘准备升级，近期将增加Anaconda和pypi源。
如果需要其他源欢迎与我们交流

**Comment by Season111** [comment]
感觉不慢啊，北外源速度还可以

**Comment by lizhaoguosina** [comment]
> 感觉不慢啊，北外源速度还可以

机房物理位置是在医校区勤博楼，这个位置访问确实问题很大

**Comment by Reset816** [comment]
已增加conda源
