### ISSUE TITLE
openEuler镜像地址失效问题

### ISSUE THREAD

**Issue by GeorgeCao-hw** [LZUOSS/Mirror#20]
各位maintainer 好：
贵站之前上线的openEuler的镜像 （ https://github.com/LZUOSS/Mirror/issues/15 ）, 地址（ https://mirror.lzu.edu.cn/openeuler/ ）近期失效了，麻烦帮忙检查确认一下。
如果需要社区这边提供任何信息或改进，烦请知会，谢谢。

**Comment by GeorgeCao-hw** [comment]
@moeyork 麻烦帮忙恢复一下，谢谢~

**Comment by GeorgeCao-hw** [comment]
@Reset816
你好，麻烦帮忙看看openEuler的镜像地址失效的问题呢，谢谢。

**Comment by Reset816** [comment]
抱歉 镜像站维护人手不太充足
之前出了点问题 暂时移除掉了，问题排查后会重新上线

**Comment by GeorgeCao-hw** [comment]
好的，感谢~~

**Comment by juzizi44** [comment]
之前镜像站同步程序鲁棒性不够，现已修复。
openEuler 镜像已重新上线
https://mirror.lzu.edu.cn/openeuler/

**Comment by GeorgeCao-hw** [comment]
@juzizi44  非常感谢~~
