### ISSUE TITLE
一些小小的建议

### ISSUE THREAD

**Issue by LuBryant** [LZUOSS/Mirror#21]
Hello，因为我是初学者，所以我感觉在openSUSE帮助文档的 openSUSE Leap 15.2 or newer 中最后再加一行 
刷新软件源
 `sudo zypper ref` 
会更完整一些。
感谢各位，辛苦啦！

**Comment by royenheart** [comment]
测试可行，已进行更新，[提交地址](https://github.com/LZUOSS/oss-mirror-help/commit/15bf77e69b3b0a7760de364a75d8fa70756206ac)。
感谢您的建议
