### ISSUE TITLE
SSL Certificate Date Invalid

### ISSUE THREAD

**Issue by detailyang** [LZUOSS/Mirror#3]
Hello.

Your site [https://mirror.lzu.edu.cn/](https://mirror.lzu.edu.cn/)'s `SSL Let's Encrypt certficate` is out of date. Can you fix this ? 

Many thanks !

BTW you guys maybe monitor whether the certificate is valid.

**Comment by lch** [comment]
We have fixed the problem. You can now use Https method to access mirror.lzu.edu.cn :).

The script for auto renew in crontab  was failed due to some unknown reason. We will monitor the problem continuously. Thanks for your advice and report.
