### ISSUE TITLE
希望可以添加centos-altarch镜像源

### ISSUE THREAD

**Issue by mingfengwuye** [LZUOSS/Mirror#4]
http://mirror.centos.org/altarch/

**Comment by mingfengwuye** [comment]
http://mirror.centos.org/altarch/

**Comment by lch** [comment]
您好，已添加 centos-altarch 仓库（ https://mirror.lzu.edu.cn/centos-altarch/ ），感谢您对兰州大学开源社区镜像站的支持。

**Comment by mingfengwuye** [comment]
十分感谢
