### ISSUE TITLE
新增优麒麟镜像申请

### ISSUE THREAD

**Issue by fenshezhuiyi** [LZUOSS/Mirror#8]
**项目名称与简介(Project Intro.)**
名称：Ubuntu Kylin
介绍：
优麒麟（Ubuntu Kylin）是由中国 CCN（由CSIP、Canonical、NUDT三方联合组建）开源创新联合实验室与天津麒麟信息技术有限公司主导开发的全球开源项目，其宗旨是通过研发用户友好的桌面环境以及特定需求的应用软件，为全球 Linux 桌面用户带来非凡的全新体验！
优麒麟操作系统是 Ubuntu 官方衍生版，得到来自 Debian、Ubuntu、Mate、LUPA 等国际社区及众多国内外社区爱好者的广泛参与和热情支持。其开发贡献者可参见Ubuntu Kylin开发者团队列表。

**上游地址与镜像方法(How to Mirror)**
rsync同步地址: user@service.ubuntukylin.com::rsync /data  
同步频率：每天自动检测一次

**其他信息(Other)**
版本：18.04.2
 镜像大小(Mirror Size)：64位（2.26G）+  32位（2.19G）
 优麒麟官方的ubuntukylin-enhanced.iso与ubuntu源里的ubuntukylin.iso的区别：ubuntukylin-enhanced.iso是基于ubuntukylin.iso的增强版本，默认安装了经过Ubuntu认可的第三方软件源中优麒麟团队与其他商业公司共同开发的商业软件（详见：https://wiki.ubuntu.com/Ubuntu%20Kylin/Ubuntu%20Kylin%20Archive），如集成wps、sogoupinyin、foxireader等流行应用软件，开箱即用，更适合用户进行一站式的办公和娱乐。
 官网：http://www.ubuntukylin.com/

**Comment by ZhiShengYuan** [comment]
好像已经有了(
